apiVersion:  apps/v1 
kind: Deployment
metadata:
 name: debian
spec:
 replicas: 1
 selector:
    matchLabels:
     app: debian
  template:
   metadata:
      labels:
        app: debian
    spec:
      containers:
      - image: itscaro/debian-ssh 
        name: debian
---
apiVersion: v1
kind: Service
metadata:
  name: debian
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "http-port-tcp"
    port: 22
 selector:
    app: debian

